version: "3.8"

services:
  db:
    restart: always
    image: mysql:8.0
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
    container_name: himo_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - himo_links
  outgame:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "./bin/outgame"
    env_file: ./.envrc.docker.local
    restart: always
    ports:
      - "5502:5502"
    depends_on:
      - db
    networks:
      - himo_links

networks:
  himo_links:
    external: true
