version: "3.8"

services:
  db:
    restart: always
    image: mysql:8.0
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    container_name: himo_db
    environment:
      MYSQL_ROOT_PASSWORD: root
  outgame:
    image: bamboooo/himo-outgame
    entrypoint: "./bin/outgame"
    env_file: ./.envrc.docker.local
    restart: always
    ports:
      - "5502:5502"
