version: "3.8"

services:
  outgame:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: "air"
    env_file: ./.envrc.docker.local
    volumes:
      - .:/himo-outgame
      - bin:/himo-outgame/bin
volumes:
  bin:
