version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Echo Test
          command: echo "CircleCI Test"
  deploy:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "33:dc:2d:6c:92:1d:07:da:26:87:c6:ff:26:ec:1d:3c"
      - run:
          name: Create docker context
          command: docker context
          environment:
            SSH_USERNAME: opc
            SSH_IP: 168.138.198.236
            SSH_PORT: 22
      - run:
          name: Deploy to dev-server
          command: |
            docker-compose --context hi-mo-dev stop
            docker-compose --context hi-mo-dev up --build -d

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only: main
