name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            bamboooo/himo-outgame:latest

  deploy:
    needs: build-image

    name: Deploy to dev server
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to dev
        run: |
          echo "$SSH_KEY" > secret_key
          chmod 600 secret_key
          ssh -o StrictHostKeyChecking=no ${ORACLE_USER}@${ORACLE_HOST} -i secret_key "cd ~/himo-outgame && git pull origin main && docker-compose stop && docker-compose -f docker-compose-prod.yml up --build -d"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          ORACLE_USER: ${{ secrets.ORACLE_USER }}
          ORACLE_HOST: ${{ secrets.ORACLE_HOST }}
