name: release

on:
  push:
    branches:
      - stable

jobs:
  build-production-image:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Set commit hash
        run: echo "::set-output name=COMMIT_HASH::${GITHUB_SHA::14}"
        id: set-commit-hash

      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            bamboooo/himo-outgame:${{ steps.set-commit-hash.outputs.COMMIT_HASH }}

  create-pr:
    needs: build-production-image

    name: Create pull request to update image tag in manifests repository
    runs-on: ubuntu-latest

    steps:
      - name: Set commit hash
        run: echo "::set-output name=COMMIT_HASH::${GITHUB_SHA::14}"
        id: set-commit-hash

      - uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.PAT }}
          repository: bamboooo-dev/himo-manifests

      - name: Init git
        run: |
          git config --local user.name ${USER_NAME}
          git config --local user.email ${USER_EMAIL}
          git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.PAT }}@github.com/bamboooo-dev/himo-manifests.git"
        env:
          USER_NAME: yamagai
          USER_EMAIL: kohei.yamamoto919@gmail.com

      - name: Update image tag
        run: |
          git checkout -b release/${{ steps.set-commit-hash.outputs.COMMIT_HASH }}
          sed -i -e "11c\  tag: ${GITHUB_SHA::14}" ./helm/outgame/values.yaml
          git add .
          git commit -m "Update image tag to ${{ steps.set-commit-hash.outputs.COMMIT_HASH }}"
          git push origin release/${{ steps.set-commit-hash.outputs.COMMIT_HASH }}

      - name: Create Pull Request
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.PAT }}" \
          "https://api.github.com/repos/bamboooo-dev/himo-manifests/pulls" \
          -d '{ "title": "Release PR", "head": "release/${{ steps.set-commit-hash.outputs.COMMIT_HASH }}", "base": "main", "body": "Update image tag to ${{ steps.set-commit-hash.outputs.COMMIT_HASH }}"}'
